export const DELETE = 'DELETE';
export const LOAD = 'LOAD';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const MOVE = 'MOVE';
export const SAVE = 'SAVE';
export const SET_CONTENT= 'SET_CONTENT';
export const SET_GITHUB = 'SET_GITHUB';
export const SET_LOCATION = 'SET_LOCATION';